on: [push]

jobs:
  build:
    name: pwa_to_apk_job
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
          export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
          nvm i 18

      - name: Install
        run: |
          npm i -g @bubblewrap/cli
          ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | bubblewrap init --manifest=https://note.223324.xyz:8888/site.webmanifest
          ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | bubblewrap build
          cp ./*.apk ..

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.apk' # Selecting all the apk files
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v1.0.0 # this is used in releases and has nothing to do with the pwa-to-apk-action
          # it is only used in softprops/action-gh-release action
